SecretsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: SecretsTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
    KeySchema:
      - AttributeName: uuid
        KeyType: HASH